name: Update RSS Feed

on:
  schedule:
    - cron: '0 16 * * 0'  # Runs every Sunday at 4 PM UTC (which is 8 AM PST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python fetch_rss.py

    - name: Commit and push changes
      run: |
        if [ -f yahoo_finance_weekly_article.xml ]; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add yahoo_finance_weekly_article.xml
          git commit -m 'Update RSS feed'
          git push
        else
          echo "RSS feed file does not exist. Skipping commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
